### ISSUE TITLE
You Cant jump with LCH

### ISSUE THREAD

**Issue by Lesgual** [kyrptonaught/LEBClientHelper#13]
**LCH have a bug that doesn't lets you jump beacuse the deafault button to Take all is space so you cant jump
for some reason LCH take all button block other buttons if you uses the same button for a function**

**Comment by S-N00B-1** [comment]
What version of LCH are you using.

**Comment by Lesgual** [comment]
![Captura de tela 2024-02-17 142533](https://github.com/Legacy-Edition-Minigames/LEMClientHelper/assets/144263713/1f275a7c-085e-4ce1-b46d-69512ad01112)

**Comment by S-N00B-1** [comment]
Does the issue still occur on 0.0.23?

**Comment by Lesgual** [comment]
i will see now

**Comment by Lesgual** [comment]
fixed gg
