### ISSUE TITLE
Armor bar fails on 3rd party battle servers.

### ISSUE THREAD

**Issue by niceEli** [kyrptonaught/LEBClientHelper#6]

**Comment by DBTDerpbox** [comment]
and this is happening on the latest datapack and serverutils build with the velocity plugin?

**Comment by DBTDerpbox** [comment]
if anything, if this happens in the toolbox rewrite ill make sure its fixed

**Comment by niceEli** [comment]
yes to the first comment

**Comment by DBTDerpbox** [comment]
Does this still happen to you on the latest version of toolbox (java branch)?

**Comment by niceEli** [comment]
ill check

**Comment by niceEli** [comment]
seems to be fixed on latest toolbox
